import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { myFont } from "./font";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${myFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
