import type { Metadata } from "next";
import { DM_Sans, Grape_Nuts } from "next/font/google";
import "./globals.css";
import { myFont } from "./font";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const grapeNuts = Grape_Nuts({
  weight: ["400"], // Grape Nuts only has one weight
  subsets: ["latin"],
  display: "swap",
  variable: "--font-grape-nuts",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${grapeNuts.variable} ${myFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
