import type { Metadata } from "next";
import { DM_Sans, Grape_Nuts } from "next/font/google";
import "./globals.css";
import { myFont, myFontMedium, myFontRegular, myFontSemibold } from "./font";

import Footer from "@/components/common/footer/footer";
import TopMenu from "@/components/common/header/TopMenu";
import BackToTop from "@/components/common/BackToTop";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
  display: "swap",
  variable: "--font-dm-sans",
});

const grapeNuts = Grape_Nuts({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-grape-nuts",
});

export const metadata: Metadata = {
  title: "Festivon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${grapeNuts.variable} ${myFont.variable} ${myFontMedium.variable} ${myFontRegular.variable} ${myFontSemibold.variable} antialiased`}
      >
        <TopMenu />
        {children}
        <Footer />
        <BackToTop />
      </body>
    </html>
  );
}
